DROP TABLE IF EXISTS dictionaries_words;

CREATE TABLE dictionaries_words
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR           NOT NULL,
    images       VARCHAR           NOT NULL
);